// Mocks generated by Mockito 5.4.6 from annotations
// in sureline/test/features/preferenecs/general_settings/sound/domain/use_cases/get_volume_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sureline/core/error/failures.dart' as _i5;
import 'package:sureline/features/preferenecs/general_settings/sound/domain/repository/sound_repository.dart'
    as _i3;
import 'package:sureline/features/preferenecs/general_settings/voice/domain/entity/voice_entity.dart'
    as _i7;
import 'package:sureline/features/preferenecs/general_settings/voice/domain/repository/voice_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SoundRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoundRepository extends _i1.Mock implements _i3.SoundRepository {
  MockSoundRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getVolume() =>
      (super.noSuchMethod(
            Invocation.method(#getVolume, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
              _FakeEither_0<_i5.Failure, double>(
                this,
                Invocation.method(#getVolume, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#setVolume, [volume]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [VoiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRepository extends _i1.Mock implements _i6.VoiceRepository {
  MockVoiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.VoiceEntity>>> getVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getVoices, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.VoiceEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i7.VoiceEntity>>(
                this,
                Invocation.method(#getVoices, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.VoiceEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>> getVoice() =>
      (super.noSuchMethod(
            Invocation.method(#getVoice, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>>.value(
                  _FakeEither_0<_i5.Failure, _i7.VoiceEntity?>(
                    this,
                    Invocation.method(#getVoice, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changeVoice(
    _i7.VoiceEntity? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeVoice, [model]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changeVoice, [model]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
