// Mocks generated by Mockito 5.4.6 from annotations
// in sureline/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sureline/common/domain/entities/collections/collection_entity.dart'
    as _i9;
import 'package:sureline/common/domain/entities/collections/favourite_entity.dart'
    as _i10;
import 'package:sureline/common/domain/entities/collections/history_entity.dart'
    as _i12;
import 'package:sureline/common/domain/entities/collections/own_quote_entity.dart'
    as _i11;
import 'package:sureline/common/domain/entities/collections/search_entity.dart'
    as _i13;
import 'package:sureline/core/error/failures.dart' as _i5;
import 'package:sureline/features/preferenecs/collections/domain/repository/collections_repository.dart'
    as _i8;
import 'package:sureline/features/preferenecs/general_settings/sound/domain/repository/sound_repository.dart'
    as _i3;
import 'package:sureline/features/preferenecs/general_settings/voice/domain/entity/voice_entity.dart'
    as _i7;
import 'package:sureline/features/preferenecs/general_settings/voice/domain/repository/voice_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SoundRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoundRepository extends _i1.Mock implements _i3.SoundRepository {
  MockSoundRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getVolume() =>
      (super.noSuchMethod(
            Invocation.method(#getVolume, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
              _FakeEither_0<_i5.Failure, double>(
                this,
                Invocation.method(#getVolume, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#setVolume, [volume]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [VoiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRepository extends _i1.Mock implements _i6.VoiceRepository {
  MockVoiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.VoiceEntity>>> getVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getVoices, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.VoiceEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i7.VoiceEntity>>(
                this,
                Invocation.method(#getVoices, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.VoiceEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>> getVoice() =>
      (super.noSuchMethod(
            Invocation.method(#getVoice, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>>.value(
                  _FakeEither_0<_i5.Failure, _i7.VoiceEntity?>(
                    this,
                    Invocation.method(#getVoice, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.VoiceEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changeVoice(
    _i7.VoiceEntity? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeVoice, [model]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changeVoice, [model]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [CollectionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionsRepository extends _i1.Mock
    implements _i8.CollectionsRepository {
  MockCollectionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>
  getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CollectionEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i9.CollectionEntity>>(
                this,
                Invocation.method(#getCollections, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveCollection(
    _i9.CollectionEntity? collection,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCollection, [collection]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#saveCollection, [collection]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeCollection(
    _i9.CollectionEntity? collection,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeCollection, [collection]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeCollection, [collection]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addFavouriteQuoteToCollection(
    int? collectionId,
    int? favouriteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addFavouriteQuoteToCollection, [
              collectionId,
              favouriteId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addFavouriteQuoteToCollection, [
                  collectionId,
                  favouriteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeFavouriteQuoteFromCollection(
    int? collectionId,
    int? favouriteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavouriteQuoteFromCollection, [
              collectionId,
              favouriteId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeFavouriteQuoteFromCollection, [
                  collectionId,
                  favouriteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.FavouriteEntity>>>
  getFavouritesOfCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavouritesOfCollection, [collectionId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i10.FavouriteEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i10.FavouriteEntity>>(
                this,
                Invocation.method(#getFavouritesOfCollection, [collectionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i10.FavouriteEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>
  getCollectionsOfFavourite(int? favouriteId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionsOfFavourite, [favouriteId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CollectionEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i9.CollectionEntity>>(
                this,
                Invocation.method(#getCollectionsOfFavourite, [favouriteId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addOwnQuoteToCollection(
    int? collectionId,
    int? ownQuoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOwnQuoteToCollection, [
              collectionId,
              ownQuoteId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addOwnQuoteToCollection, [
                  collectionId,
                  ownQuoteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeOwnQuoteFromCollection(
    int? collectionId,
    int? ownQuoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeOwnQuoteFromCollection, [
              collectionId,
              ownQuoteId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeOwnQuoteFromCollection, [
                  collectionId,
                  ownQuoteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.OwnQuoteEntity>>>
  getOwnQuotesOfCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnQuotesOfCollection, [collectionId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i11.OwnQuoteEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i11.OwnQuoteEntity>>(
                this,
                Invocation.method(#getOwnQuotesOfCollection, [collectionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i11.OwnQuoteEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>
  getCollectionsOfOwnQuote(int? ownQuoteId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionsOfOwnQuote, [ownQuoteId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CollectionEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i9.CollectionEntity>>(
                this,
                Invocation.method(#getCollectionsOfOwnQuote, [ownQuoteId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addHistoryToCollection(
    int? collectionId,
    int? quoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addHistoryToCollection, [collectionId, quoteId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addHistoryToCollection, [
                  collectionId,
                  quoteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeHistoryFromCollection(
    int? collectionId,
    int? quoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeHistoryFromCollection, [
              collectionId,
              quoteId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeHistoryFromCollection, [
                  collectionId,
                  quoteId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>
  getCollectionsOfHistory(int? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionsOfHistory, [historyId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CollectionEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i9.CollectionEntity>>(
                this,
                Invocation.method(#getCollectionsOfHistory, [historyId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.HistoryEntity>>>
  getHistoryOfCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoryOfCollection, [collectionId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i12.HistoryEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i12.HistoryEntity>>(
                this,
                Invocation.method(#getHistoryOfCollection, [collectionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i12.HistoryEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addSearchToCollection(
    int? collectionId,
    int? searchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSearchToCollection, [collectionId, searchId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addSearchToCollection, [
                  collectionId,
                  searchId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeSearchFromCollection(
    int? collectionId,
    int? searchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeSearchFromCollection, [
              collectionId,
              searchId,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeSearchFromCollection, [
                  collectionId,
                  searchId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>
  getCollectionsOfSearch(int? searchId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionsOfSearch, [searchId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CollectionEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i9.CollectionEntity>>(
                this,
                Invocation.method(#getCollectionsOfSearch, [searchId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.CollectionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i13.SearchEntity>>>
  getSearchOfCollection(int? collectionId, {required bool? isPremium}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSearchOfCollection,
              [collectionId],
              {#isPremium: isPremium},
            ),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i13.SearchEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i13.SearchEntity>>(
                this,
                Invocation.method(
                  #getSearchOfCollection,
                  [collectionId],
                  {#isPremium: isPremium},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i13.SearchEntity>>>);
}
